package xmu.oomall.mapper;

import org.apache.ibatis.annotations.Mapper;
import xmu.oomall.domain.po.BrandPo;

import java.util.List;

/**
 * @author zhang
 */
@Mapper
public interface BrandMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brand
     *
     * @mbg.generated Mon Dec 09 20:12:20 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brand
     *
     * @mbg.generated Mon Dec 09 20:12:20 CST 2019
     */
    int insert(BrandPo record);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brand
     *
     * @mbg.generated Mon Dec 09 20:12:20 CST 2019
     */
    BrandPo selectByPrimaryKey(Integer id);

    List<BrandPo> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brand
     *
     * @mbg.generated Mon Dec 09 20:12:20 CST 2019
     */
    int updateByPrimaryKey(BrandPo record);
}