package xmu.oomall.mapper;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import xmu.oomall.domain.po.BrandPo;

import java.util.List;

/**
 * @author zhang
 */
@Mapper
public interface BrandMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brand
     *
     * @mbg.generated Mon Dec 09 20:12:20 CST 2019
     */
    int deleteByPrimaryKey(@Param("id") Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brand
     *
     * @mbg.generated Mon Dec 09 20:12:20 CST 2019
     */
    int insert(@Param("brand") BrandPo record);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brand
     *
     * @mbg.generated Mon Dec 09 20:12:20 CST 2019
     */
    BrandPo selectByPrimaryKey(@Param("id") Integer id);

    /**
     * 查询所有品牌
     *
     * @return 品牌列表
     */
    List<BrandPo> selectAll();

    List<BrandPo> selectByCondition(@Param("id") Integer id, @Param("name") String name);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brand
     *
     * @mbg.generated Mon Dec 09 20:12:20 CST 2019
     */
    int updateByPrimaryKey(@Param("brand") BrandPo record);
}