package xmu.oomall.mapper;

import org.apache.ibatis.annotations.Mapper;
import xmu.oomall.domain.GoodsCategory;
import xmu.oomall.domain.po.GoodsCategoryPo;

import java.util.List;

/**
 * @author zhang
 */
@Mapper
public interface GoodsCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_category
     *
     * @mbg.generated Mon Dec 09 20:12:20 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_category
     *
     * @mbg.generated Mon Dec 09 20:12:20 CST 2019
     */
    int insert(GoodsCategoryPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_category
     *
     * @mbg.generated Mon Dec 09 20:12:20 CST 2019
     */
    GoodsCategoryPo selectByPrimaryKey(Integer id);

    /**
     * 查询一级分类
     * @return 一级分类列表
     */
    List<GoodsCategoryPo> selectOneLevelGoodsCategories();

    /**
     * 根据父id查询他的子分类
     * @param pid
     * @return pid对应分类的子分类列表
     */
    List<GoodsCategoryPo> selectSecondLevelGoodsCategories(Integer pid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_category
     *
     * @mbg.generated Mon Dec 09 20:12:20 CST 2019
     */
    int updateByPrimaryKey(GoodsCategoryPo record);
}