package xmu.oomall.mapper;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import xmu.oomall.domain.po.GoodsPo;

import java.util.List;

/**
 * @author zhang
 */
@Mapper
public interface GoodsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods
     *
     * @mbg.generated Mon Dec 09 20:12:20 CST 2019
     */
    int deleteByPrimaryKey(@Param("id") Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods
     *
     * @mbg.generated Mon Dec 09 20:12:20 CST 2019
     */
    int insert(@Param("record") GoodsPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods
     *
     * @mbg.generated Mon Dec 09 20:12:20 CST 2019
     */
    GoodsPo selectByPrimaryKey(@Param("id") Integer id);

    /**
     * 通过类别查询
     *
     * @param categoryId
     * @return 对应的商品列表
     */
    List<GoodsPo> selectByCategoryId(Integer categoryId);

    /**
     * 条件查询
     *
     * @param goodsSn
     * @param name
     * @param statusCode
     * @return goodsPo列表
     */
    List<GoodsPo> selectByCondition(@Param("goodsSn") String goodsSn, @Param("name") String name, @Param("statusCode") Integer statusCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods
     *
     * @mbg.generated Mon Dec 09 20:12:20 CST 2019
     */
    int updateByPrimaryKey(@Param("record") GoodsPo record);

    /**
     * 将商品品牌brandId的商品的品牌置为空值
     *
     * @param brandId
     * @return 更新的商品数量
     */
    int cleanBrand(@Param("brandId") Integer brandId);

    /**
     * 将类别为categoryId的商品类别置为空值
     *
     * @param categoryId
     * @return 更新的商品数量
     */
    int cleanCategory(@Param("categoryId") Integer categoryId);
}