package xmu.oomall.mapper;

import org.apache.ibatis.annotations.Mapper;
import xmu.oomall.domain.Goods;
import xmu.oomall.domain.impl.GoodsImpl;

/**
 * @author zhang
 */
@Mapper
public interface GoodsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods
     *
     * @mbg.generated Mon Dec 09 20:12:20 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods
     *
     * @mbg.generated Mon Dec 09 20:12:20 CST 2019
     */
    int insert(GoodsImpl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods
     *
     * @mbg.generated Mon Dec 09 20:12:20 CST 2019
     */
    int insertSelective(Goods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods
     *
     * @mbg.generated Mon Dec 09 20:12:20 CST 2019
     */
    GoodsImpl selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods
     *
     * @mbg.generated Mon Dec 09 20:12:20 CST 2019
     */
    int updateByPrimaryKeySelective(GoodsImpl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods
     *
     * @mbg.generated Mon Dec 09 20:12:20 CST 2019
     */
    int updateByPrimaryKey(GoodsImpl record);
}