package xmu.oomall.mapper;

import org.apache.ibatis.annotations.Mapper;
import xmu.oomall.domain.po.ProductPo;

import java.util.List;

/**
 * @author zhang
 */
@Mapper
public interface ProductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Mon Dec 09 20:12:20 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Mon Dec 09 20:12:20 CST 2019
     */
    int insert(ProductPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Mon Dec 09 20:12:20 CST 2019
     */

    /**
     * 插入products列表
     * @param products
     * @return 插入的数量
     */
    int insertProducts(List<ProductPo> products);

    int insertSelective(ProductPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Mon Dec 09 20:12:20 CST 2019
     */
    ProductPo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Mon Dec 09 20:12:20 CST 2019
     */
    int updateByPrimaryKeySelective(ProductPo record);

    /**
     * 根据商品id返回对应的product列表
     * @param goodsId
     * goodsId
     * @return
     */
    List<ProductPo> selectByGoodsId(Integer goodsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Mon Dec 09 20:12:20 CST 2019
     */
    int updateByPrimaryKey(ProductPo record);

}
