package xmu.oomall.mapper;

import org.apache.ibatis.annotations.Mapper;
import xmu.oomall.domain.Product;

import java.util.List;

/**
 * @author zhang
 */
@Mapper
public interface ProductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Mon Dec 09 20:12:20 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Mon Dec 09 20:12:20 CST 2019
     */
    int insert(Product record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Mon Dec 09 20:12:20 CST 2019
     */
    int insertSelective(Product record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Mon Dec 09 20:12:20 CST 2019
     */
    Product selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Mon Dec 09 20:12:20 CST 2019
     */
    int updateByPrimaryKeySelective(Product record);

    /**
     * 根据商品id返回对应的product列表
     * @param goodsId
     * goodsId
     * @return
     */
    List<Product> selectByGoodsId(Integer goodsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Mon Dec 09 20:12:20 CST 2019
     */
    int updateByPrimaryKey(Product record);
}
