package xmu.oomall.mapper;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;
import xmu.oomall.domain.po.ProductPo;

import java.util.List;

/**
 * @author zhang
 */
@Component
@Mapper
public interface ProductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Mon Dec 09 20:12:20 CST 2019
     */
    int deleteByPrimaryKey(@Param("id") Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Mon Dec 09 20:12:20 CST 2019
     */
    int insert(@Param("product") ProductPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Mon Dec 09 20:12:20 CST 2019
     */

    /**
     * 插入products列表
     *
     * @param products
     * @return 插入的数量
     */
    int insertProducts(@Param("products") List<ProductPo> products);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Mon Dec 09 20:12:20 CST 2019
     */
    ProductPo selectByPrimaryKey(@Param("id") Integer id);

    /**
     * 根据商品id返回对应的product列表
     *
     * @param goodsId goodsId
     * @return
     */
    List<ProductPo> selectByGoodsId(@Param("goodsId") Integer goodsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Mon Dec 09 20:12:20 CST 2019
     */
    /**
     * 插入一条product记录
     *
     * @param record productPo
     * @return id
     */
    int updateByPrimaryKey(@Param("product") ProductPo record);

}
