server:
  port: 8088

spring:
  application:
    name: GoodsInfoService
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://handsomeyida.xyz:3306/oomall?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: oomallUser
    password: 123456
    druid:
      #初始化时建立物理连接的个数
      initial-size: 3
       neophyte
        最小连接池数量
      min-idle: 3
      #最大连接池数量
      max-active: 10
      #获取连接时最大等待时间
      max-wait: 60000
      #配置监控页面访问登录名及密码
      stat-view-servlet:
        login-username: admin
        login-password: 123456
      filter:
        stat:
          #是否开启慢sql查询监控
          log-slow-sql: true
          #慢SQL执行时间
          slow-sql-millis: 100
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: localhost

eureka:
  client:
    service-url:
      defaultZone: http://handsomeyida.xyz:8761/eureka
  instance:
    preferIpAddress: true
    instance-id: GoodsInfoService8088
    ip-address: 39.106.136.106


mybatis:
  type-aliases-package: xmu.oomall.domain.po
  mapper-locations: classpath:xmu.oomall.mapper/*.xml
  configuration:
    map-underscore-camel-case: true

oomall:
  #redis缓存失效时间，单位秒
  redisexpiretime: 30
  #预提库存数量
  predeductQty: 3
